### ISSUE TITLE
Whether to include Appendix A in v1.0

### ISSUE THREAD

**Issue by Henry-WattTime** [Green-Software-Foundation/sci#283]
Should we include the appendix as currently drafted in the first specification release?

**Comment by seanmcilroy29** [comment]
Appendix A should be added as the Revision History

**Appendix A: Revision History**

**Comment by Henry-WattTime** [comment]
Currently in dev, Appendix A is additional reporting requirements. (https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Appendix_A_Further_Information_on_Reporting_Requirements.md)
I think we should defer the reporting appendix until we have the chance to fully develop the reporting approach, outside of the spec (maybe reclaim the project from the reporting project as a central standards WG project). 
Thoughts?

**Comment by Henry-WattTime** [comment]
Working group has agreed that the reporting requirements should be removed from Appendix A (and moved to other repo focused on reporting), now appendix A will be used inside the document at the bottom to record versioning.

**Comment by Henry-WattTime** [comment]
WG: also remove cast study template

**Comment by atg-abhishek** [comment]
@Henry-WattTime what was the decision on the reporting requirements?

**Comment by Henry-WattTime** [comment]
It was to remove this from the specification. (probably also the template?)

**Comment by Sealjay** [comment]
https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/317 - just seen this issue. is there a repo for the reporting standards to go into? keen to have a place to reference it from, even if separated from the standard, as we're actively starting to create reports for software

**Comment by Henry-WattTime** [comment]
WG approved _moving_ appendix to reporting project repository. @Sealjay to move.

**Comment by seanmcilroy29** [comment]
see Issue #331

**Comment by atg-abhishek** [comment]
@seanmcilroy29 can we close this out?
