### ISSUE TITLE
[Cosmetic] Remove Peter Drucker's quote "If you can't measure it, you can't improve it."

### ISSUE THREAD

**Issue by bertysentry** [Green-Software-Foundation/sci#349]
> **Note**
> I plan on submitting more meaningful change proposals, but this one stroke me first when reading the specification.

In `Software_Carbon_Intensity_Specification.md`, we need to remove the introductory quote from Peter Drucker.

Peter Drucker actually never said "If you can't measure it, you can't improve it.". See https://www.drucker.institute/thedx/measurement-myopia for more information.

**Comment by seanmcilroy29** [comment]
See #350
